language: node_js

node_js:
  - "8"

env:
  matrix:
    - TEST_TYPE=test
    - TEST_TYPE=build

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    elif [ "$TEST_TYPE" = build ]; then
      npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master